Upload artificats. Add jupyter creation mannual task

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,10 +38,20 @@ jobs:
 
   job-build-project:
     runs-on: ubuntu-latest
+    permissions:
+      # required for sarif upload
+      security-events: write
+
     steps:
 
       - name: Check out repository
         uses: actions/checkout@v3
+
+      - name: Start display server
+        run: |
+          sudo apt-get install xvfb
+          Xvfb :99 &
+          echo "DISPLAY=:99" >> $GITHUB_ENV
 
       - name: Setup MATLAB
         uses: matlab-actions/setup-matlab@v1
@@ -52,3 +62,26 @@ jobs:
         uses: matlab-actions/run-build@v1
         with:
           tasks: qualify
+
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: results/issues.sarif
+          category: matlab-analysis
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'results/test-results.xml'
+
+      - name: Upload Test Report  
+        uses: actions/upload-artifact@v2
+        with:
+          name:  Test Results
+          path: results/test-results.pdf
+
+      - uses: 5monkeys/cobertura-action@master
+        with:
+          path: results/coverage.xml
+
